# config/packages/framework.yaml
framework:
    secret: '%env(APP_SECRET)%'
    session: true

    validation:
        enabled: true
        enable_attributes: true
        email_validation_mode: 'html5'


when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
