# config/packages/knp_paginator.yaml

knp_paginator:
  page_range: 5                       # Nombre de pages affichées dans la pagination
  default_options:
    page_name: page                # Le nom du paramètre GET pour la page (ex: ?page=2)
    sort_field_name: sort          # Nom du champ de tri dans l’URL (optionnel)
    sort_direction_name: direction # ASC ou DESC
    distinct: true                 # Pour éviter les doublons avec des jointures
  template:
    pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig'
    sortable: '@KnpPaginator/Pagination/sortable_link.html.twig'
