security:
    password_hashers:
        App\Entity\Utilisateur:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                success_handler: App\Security\LoginSuccessHandler
            logout:
                path: app_logout
                target: app_home # ou "/" si tu n’as pas encore créé la route "app_home"

    access_control:
        # --- Public (lecture seule + auth pages) ---
        - { path: ^/login$, roles: PUBLIC_ACCESS }
        - { path: ^/logout$, roles: PUBLIC_ACCESS }
        - { path: ^/inscription$, roles: PUBLIC_ACCESS }

        # Contenus publics en lecture
        - { path: ^/plantes, roles: PUBLIC_ACCESS }
        - { path: ^/tisanes, roles: PUBLIC_ACCESS }
        - { path: ^/articles/\d+$, roles: PUBLIC_ACCESS }
        - { path: ^/articles, roles: PUBLIC_ACCESS }
        - { path: ^/recettes, roles: PUBLIC_ACCESS }
        - { path: ^/$, roles: PUBLIC_ACCESS }

        # --- Espace utilisateur (doit être loggué) ---
        - { path: ^/utilisateurs/mon-profil/modifier$, roles: ROLE_USER }
        - { path: ^/utilisateurs/mon-profil$, roles: ROLE_USER }
        - { path: ^/utilisateurs/dashboard$, roles: ROLE_USER }

        # Création/édition de contenus (user ou admin)
        - { path: ^/recettes/new$, roles: [ ROLE_USER, ROLE_ADMIN ] }
        - { path: ^/recettes/\d+/edit$, roles: [ ROLE_USER, ROLE_ADMIN ] }
        - { path: ^/articles/new$, roles: [ ROLE_USER, ROLE_ADMIN ] }
        - { path: ^/articles/\d+/edit$, roles: [ ROLE_USER, ROLE_ADMIN ] }
        - { path: ^/commentaires, roles: [ ROLE_USER, ROLE_ADMIN ] }

        # --- Zone admin uniquement ---
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/utilisateurs/ajouter$, roles: ROLE_ADMIN }
        - { path: ^/utilisateurs/\d+/modifier$, roles: ROLE_ADMIN }
        - { path: ^/utilisateurs/\d+$, roles: ROLE_ADMIN }
        - { path: ^/utilisateurs$, roles: ROLE_ADMIN }                 # liste des utilisateurs
        - { path: ^/articles/\d+/valider$, roles: ROLE_ADMIN }
        - { path: ^/recettes/\d+/valider$, roles: ROLE_ADMIN }
        - { path: ^/recettes/admin, roles: ROLE_ADMIN }
        - { path: ^/commentaires/signales$, roles: ROLE_ADMIN }
        - { path: ^/commentaires/designaler$, roles: ROLE_ADMIN }





when@test:
    security:
        password_hashers:
            App\Entity\Utilisateur:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
