security:
    password_hashers:
        App\Entity\Utilisateur:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
            logout:
                path: app_logout
                target: app_home # ou "/" si tu n’as pas encore créé la route "app_home"

    access_control:
        #- { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/articles, roles: ROLE_USER }
        - { path: ^/recettes, roles: ROLE_USER }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: PUBLIC_ACCESS }

when@test:
    security:
        password_hashers:
            App\Entity\Utilisateur:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
