# Dockerfile.web
# 1) On définit l’argument
ARG APP_IMAGE

# 2) On crée un stage nommé "apppub" basé sur l’image app
FROM ${APP_IMAGE} AS apppub

# 3) Stage final Nginx
FROM nginx:1.27

# 4) On copie le dossier public depuis le stage "apppub"
COPY --from=apppub /var/www/html/public /var/www/html/public

# 5) Conf Nginx
COPY docker/nginx.prod.conf /etc/nginx/conf.d/default.conf
